### ISSUE TITLE
Add bitwarden to Password Managers?

### ISSUE THREAD

**Issue by huyz** [nschloe/gh-trends#104]
https://github.com/bitwarden/server

**Comment by nschloe** [comment]
Take a look at https://github.com/nschloe/gh-trends/issues/101#issuecomment-1011343800. If more issues are opened, I'm going to have to block you.

**Comment by huyz** [comment]
Sorry, I only just saw your message. I'm done anyway

**Comment by nschloe** [comment]
Added.
